package io.github.veronikapj.autodoc

import ai.koog.prompt.executor.clients.anthropic.AnthropicLLMClient
import ai.koog.prompt.executor.llms.MultiLLMPromptExecutor
import io.github.veronikapj.autodoc.a2a.A2AClientManager
import io.github.veronikapj.autodoc.a2a.A2AServerManager
import io.github.veronikapj.autodoc.agent.OrchestratorAgent
import io.github.veronikapj.autodoc.agent.specialist.*
import io.github.veronikapj.autodoc.config.ConfigLoader
import io.github.veronikapj.autodoc.platform.AgentType
import io.github.veronikapj.autodoc.platform.PlatformConfig
import io.github.veronikapj.autodoc.platform.TemplateResolver
import io.github.veronikapj.autodoc.tools.GitHubTool
import kotlinx.coroutines.runBlocking

fun main(args: Array<String>) = runBlocking {
    val prNumber = args.firstOrNull()?.toIntOrNull()
        ?: error("PR 번호를 인자로 전달해주세요. 예: ./gradlew run --args='42'")

    val anthropicKey = System.getenv("ANTHROPIC_API_KEY")
        ?: error("ANTHROPIC_API_KEY 환경변수가 없습니다")
    val githubToken = System.getenv("GITHUB_TOKEN")
        ?: error("GITHUB_TOKEN 환경변수가 없습니다")
    val repoName = System.getenv("GITHUB_REPOSITORY")
        ?: error("GITHUB_REPOSITORY 환경변수가 없습니다")
    val repoPath = System.getenv("TARGET_REPO_PATH") ?: "."

    // 설정 로드
    val config = ConfigLoader.load(repoPath)
    println("AutoDoc Agent 시작")
    println("   플랫폼: ${config.platform}")
    println("   PR: #$prNumber")
    println("   레포: $repoName")

    // 공통 컴포넌트
    val client = AnthropicLLMClient(anthropicKey)
    val executor = MultiLLMPromptExecutor(client)
    val templateResolver = TemplateResolver(config.platform, repoPath)
    val platformConfig = PlatformConfig(config.platform)
    val githubTool = GitHubTool(githubToken)

    // 전문 에이전트 생성
    val specialists = mapOf(
        AgentType.README to ReadmeAgent(executor, templateResolver),
        AgentType.ARCH_DOC to ArchDocAgent(executor, templateResolver),
        AgentType.API_DOC to ApiDocAgent(executor, templateResolver),
        AgentType.TEST_DOC to TestDocAgent(executor, templateResolver),
        AgentType.CHANGELOG to ChangelogAgent(executor, templateResolver),
        AgentType.SETUP_DOC to SetupDocAgent(executor, templateResolver),
        AgentType.SPEC_DOC to SpecDocAgent(executor, templateResolver),
    )

    // A2A 서버 시작
    println("\nA2A 서버 시작 중...")
    val serverManager = A2AServerManager(specialists)
    val ports = serverManager.start()

    // A2A 클라이언트 연결
    val clientManager = A2AClientManager()
    clientManager.connectAll(ports)

    try {
        // Orchestrator 실행
        val orchestrator = OrchestratorAgent(clientManager, platformConfig, githubTool, repoName)
        val changedDocs = orchestrator.run(prNumber)

        if (changedDocs.isEmpty()) {
            println("\n업데이트할 문서 없음. 종료합니다.")
            return@runBlocking
        }

        println("\n업데이트된 문서 ${changedDocs.size}개:")
        changedDocs.keys.forEach { println("   - $it") }

        // 문서 PR 생성
        val summary = buildPRSummary(changedDocs.keys.toList(), prNumber)
        githubTool.createDocsPR(repoName, "main", prNumber, changedDocs, summary)

        println("\n완료!")
    } finally {
        serverManager.stop()
    }
}

private fun buildPRSummary(updatedDocs: List<String>, prNumber: Int) = """
    ## AutoDoc Agent 자동 문서 업데이트

    PR #${prNumber}의 변경사항을 분석하여 다음 문서를 업데이트했습니다:

    ${updatedDocs.joinToString("\n") { "- `$it`" }}

    > 내용을 검토 후 머지해주세요.

    Generated by [AutoDoc Agent](https://github.com/Veronikapj/autodoc-agent)
""".trimIndent()
